version: '3'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/reviro
    environment:
      - DB_HOST=pgdb
      - DB_NAME=reviro_db
      - DB_USER=yountuan
      - DB_PASSWORD=1
      - TOKEN 
    ports:
      - 8000:8000

    command: >
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 su.py && 
      python3 manage.py runserver 0.0.0.0:8000

    depends_on:
      - pgdb

  pgdb:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=reviro_db
      - POSTGRES_USER=yountuan
      - POSTGRES_PASSWORD=1
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
