# Generated by Django 4.2.10 on 2024-03-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='opening_hours',
            field=models.TimeField(default='06:00'),
        ),
    ]
