# Generated by Django 4.2.10 on 2024-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_start', '0003_alter_location_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closing_hours',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_hours',
            field=models.TimeField(default='00:00'),
        ),
    ]
