# Generated by Django 4.2.10 on 2024-03-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech_start', '0004_location_closing_hours_alter_location_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='establishment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech_start.establishment'),
            preserve_default=False,
        ),
    ]
